#!/usr/bin/env node

const express = require('express');

var app = express();
app.use(/^\/dist/, express.static(`${__dirname}/dist`));
app.use(/^\/lib/, express.static(`${__dirname}/lib`));
app.get('/test/data', (req, res) =>
	res.json(require(`${__dirname}/test/PrivateReportResult.json`)).end());
app.listen(8080);